/**
 * Generated by orval v8.5.3 🍺
 * API Schemas using Zod validation
 */
import * as zod from "zod";

// ==================== HEALTH ====================

export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

// ==================== USERS ====================

export const GetMyProfileResponse = zod.object({
  id: zod.string(),
  clerkId: zod.string(),
  email: zod.string(),
  name: zod.string().nullish(),
  phone: zod.string().nullish(),
  role: zod.enum(["user", "admin", "owner"]),
  createdAt: zod.string(),
});

export const ListUsersResponseItem = zod.object({
  id: zod.string(),
  clerkId: zod.string(),
  email: zod.string(),
  name: zod.string().nullish(),
  phone: zod.string().nullish(),
  role: zod.enum(["user", "admin", "owner"]),
  createdAt: zod.string(),
});
export const ListUsersResponse = zod.array(ListUsersResponseItem);

export const UpdateUserRoleParams = zod.object({
  userId: zod.coerce.string(),
});

export const UpdateUserRoleBody = zod.object({
  role: zod.enum(["user", "admin", "owner"]),
});

export const UpdateUserRoleResponse = zod.object({
  id: zod.string(),
  clerkId: zod.string(),
  email: zod.string(),
  name: zod.string().nullish(),
  phone: zod.string().nullish(),
  role: zod.enum(["user", "admin", "owner"]),
  createdAt: zod.string(),
});

// ==================== INQUIRIES ====================

export const ListInquiriesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  phone: zod.string().nullish(),
  whatsapp: zod.string().nullish(),
  subject: zod.string(),
  message: zod.string(),
  status: zod.enum(["pending", "contacted", "resolved"]),
  createdAt: zod.string(),
});
export const ListInquiriesResponse = zod.array(ListInquiriesResponseItem);

export const CreateInquiryBody = zod.object({
  name: zod.string(),
  email: zod.string(),
  phone: zod.string().optional(),
  whatsapp: zod.string().optional(),
  subject: zod.string(),
  message: zod.string(),
});

export const GetInquiryParams = zod.object({
  inquiryId: zod.coerce.number(),
});

export const GetInquiryResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  phone: zod.string().nullish(),
  whatsapp: zod.string().nullish(),
  subject: zod.string(),
  message: zod.string(),
  status: zod.enum(["pending", "contacted", "resolved"]),
  createdAt: zod.string(),
});

export const UpdateInquiryParams = zod.object({
  inquiryId: zod.coerce.number(),
});

export const UpdateInquiryBody = zod.object({
  status: zod.enum(["pending", "contacted", "resolved"]).optional(),
  notes: zod.string().optional(),
});

export const UpdateInquiryResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  phone: zod.string().nullish(),
  whatsapp: zod.string().nullish(),
  subject: zod.string(),
  message: zod.string(),
  status: zod.enum(["pending", "contacted", "resolved"]),
  createdAt: zod.string(),
});

export const DeleteInquiryParams = zod.object({
  inquiryId: zod.coerce.number(),
});

// ==================== PROGRAMS ====================

export const ListProgramsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  country: zod.string(),
  duration: zod.string(),
  imageUrl: zod.string().nullish(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});
export const ListProgramsResponse = zod.array(ListProgramsResponseItem);

export const CreateProgramBody = zod.object({
  title: zod.string(),
  description: zod.string(),
  country: zod.string(),
  duration: zod.string(),
  imageUrl: zod.string().optional(),
  featured: zod.boolean().optional(),
});

export const GetProgramParams = zod.object({
  programId: zod.coerce.number(),
});

export const GetProgramResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  country: zod.string(),
  duration: zod.string(),
  imageUrl: zod.string().nullish(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});

export const UpdateProgramParams = zod.object({
  programId: zod.coerce.number(),
});

export const UpdateProgramBody = zod.object({
  title: zod.string().optional(),
  description: zod.string().optional(),
  country: zod.string().optional(),
  duration: zod.string().optional(),
  imageUrl: zod.string().optional(),
  featured: zod.boolean().optional(),
});

export const UpdateProgramResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  country: zod.string(),
  duration: zod.string(),
  imageUrl: zod.string().nullish(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});

export const DeleteProgramParams = zod.object({
  programId: zod.coerce.number(),
});

// ==================== GALLERY ====================

export const ListGalleryImagesResponseItem = zod.object({
  id: zod.number(),
  url: zod.string(),
  caption: zod.string().nullish(),
  category: zod.string().nullish(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
});
export const ListGalleryImagesResponse = zod.array(
  ListGalleryImagesResponseItem,
);

export const CreateGalleryImageBody = zod.object({
  url: zod.string(),
  caption: zod.string().optional(),
  category: zod.string().optional(),
  sortOrder: zod.number().optional(),
});

export const UpdateGalleryImageParams = zod.object({
  imageId: zod.coerce.number(),
});

export const UpdateGalleryImageBody = zod.object({
  url: zod.string().optional(),
  caption: zod.string().optional(),
  category: zod.string().optional(),
  sortOrder: zod.number().optional(),
});

export const UpdateGalleryImageResponse = zod.object({
  id: zod.number(),
  url: zod.string(),
  caption: zod.string().nullish(),
  category: zod.string().nullish(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
});

export const DeleteGalleryImageParams = zod.object({
  imageId: zod.coerce.number(),
});

// ==================== TESTIMONIALS ====================

export const ListTestimonialsResponseItem = zod.object({
  id: zod.number(),
  studentName: zod.string(),
  country: zod.string(),
  program: zod.string().nullish(),
  message: zod.string(),
  avatarUrl: zod.string().nullish(),
  rating: zod.number(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});
export const ListTestimonialsResponse = zod.array(ListTestimonialsResponseItem);

export const CreateTestimonialBody = zod.object({
  studentName: zod.string(),
  country: zod.string(),
  program: zod.string().optional(),
  message: zod.string(),
  avatarUrl: zod.string().optional(),
  rating: zod.number(),
  featured: zod.boolean().optional(),
});

export const UpdateTestimonialParams = zod.object({
  testimonialId: zod.coerce.number(),
});

export const UpdateTestimonialBody = zod.object({
  studentName: zod.string().optional(),
  country: zod.string().optional(),
  program: zod.string().optional(),
  message: zod.string().optional(),
  avatarUrl: zod.string().optional(),
  rating: zod.number().optional(),
  featured: zod.boolean().optional(),
});

export const UpdateTestimonialResponse = zod.object({
  id: zod.number(),
  studentName: zod.string(),
  country: zod.string(),
  program: zod.string().nullish(),
  message: zod.string(),
  avatarUrl: zod.string().nullish(),
  rating: zod.number(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});

export const DeleteTestimonialParams = zod.object({
  testimonialId: zod.coerce.number(),
});

// ==================== NOTIFICATIONS ====================

export const SendNotificationBody = zod.object({
  channel: zod.enum(["email", "whatsapp", "both"]),
  recipientEmail: zod.string().nullish(),
  recipientPhone: zod.string().nullish(),
  subject: zod.string(),
  message: zod.string(),
});

export const SendNotificationResponse = zod.object({
  success: zod.boolean(),
  emailSent: zod.boolean(),
  whatsappSent: zod.boolean(),
  message: zod.string(),
});

// ==================== ADMIN STATS ====================

export const GetAdminStatsResponse = zod.object({
  totalUsers: zod.number(),
  totalInquiries: zod.number(),
  pendingInquiries: zod.number(),
  totalPrograms: zod.number(),
  totalGalleryImages: zod.number(),
  totalTestimonials: zod.number(),
  recentInquiries: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      email: zod.string(),
      phone: zod.string().nullish(),
      whatsapp: zod.string().nullish(),
      subject: zod.string(),
      message: zod.string(),
      status: zod.enum(["pending", "contacted", "resolved"]),
      createdAt: zod.string(),
    }),
  ),
});

// ==================== CONSULTANT ====================

export const ListConsultantsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  specialization: zod.string(),
  bio: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  email: zod.string(),
  phone: zod.string().nullish(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});
export const ListConsultantsResponse = zod.array(ListConsultantsResponseItem);

export const CreateConsultantBody = zod.object({
  name: zod.string(),
  specialization: zod.string(),
  bio: zod.string().optional(),
  imageUrl: zod.string().optional(),
  email: zod.string(),
  phone: zod.string().optional(),
  featured: zod.boolean().optional(),
});

export const UpdateConsultantParams = zod.object({
  consultantId: zod.coerce.number(),
});

export const UpdateConsultantBody = zod.object({
  name: zod.string().optional(),
  specialization: zod.string().optional(),
  bio: zod.string().optional(),
  imageUrl: zod.string().optional(),
  email: zod.string().optional(),
  phone: zod.string().optional(),
  featured: zod.boolean().optional(),
});

export const DeleteConsultantParams = zod.object({
  consultantId: zod.coerce.number(),
});

// ==================== DESTINATION ====================

export const ListDestinationsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string(),
  country: zod.string(),
  imageUrl: zod.string().nullish(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});
export const ListDestinationsResponse = zod.array(ListDestinationsResponseItem);

export const CreateDestinationBody = zod.object({
  name: zod.string(),
  description: zod.string(),
  country: zod.string(),
  imageUrl: zod.string().optional(),
  featured: zod.boolean().optional(),
});

export const GetDestinationParams = zod.object({
  destinationId: zod.coerce.number(),
});

export const GetDestinationResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string(),
  country: zod.string(),
  imageUrl: zod.string().nullish(),
  featured: zod.boolean(),
  createdAt: zod.string(),
});

export const UpdateDestinationParams = zod.object({
  destinationId: zod.coerce.number(),
});

export const UpdateDestinationBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().optional(),
  country: zod.string().optional(),
  imageUrl: zod.string().optional(),
  featured: zod.boolean().optional(),
});

export const DeleteDestinationParams = zod.object({
  destinationId: zod.coerce.number(),
});

// ==================== APPOINTMENTS ====================

export const CreateAppointmentBody = zod.object({
  name: zod.string(),
  email: zod.string(),
  phone: zod.string(),
  destination: zod.string().optional(),
  preferredDate: zod.string(),
  preferredTime: zod.string(),
  notes: zod.string().optional(),
});

export const ListAppointmentsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  phone: zod.string(),
  destination: zod.string().nullish(),
  preferredDate: zod.string(),
  preferredTime: zod.string(),
  notes: zod.string().nullish(),
  status: zod.enum(["pending", "confirmed", "cancelled"]),
  createdAt: zod.string(),
});
export const ListAppointmentsResponse = zod.array(ListAppointmentsResponseItem);

// ==================== SITE CONTENT ====================

export const GetSiteContentResponse = zod.object({
  homeTitle: zod.string(),
  homeDescription: zod.string(),
  servicesDescription: zod.string(),
  contactEmail: zod.string(),
});

export const UpdateSiteContentBody = zod.object({
  homeTitle: zod.string().optional(),
  homeDescription: zod.string().optional(),
  servicesDescription: zod.string().optional(),
  contactEmail: zod.string().optional(),
});
